# Generated by Django 4.2.16 on 2024-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment')], max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=200)),
            ],
        ),
    ]
