# Generated by Django 4.2.16 on 2024-11-15 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0002_expensemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemanager',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
