# Generated by Django 4.2.16 on 2024-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0003_expensemanager_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemanager',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Bill', 'Bill'), ('Health', 'Health'), ('Education', 'Education'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Finance', 'Finance'), ('Lifestyle', 'Lifestyle'), ('Music', 'Music'), ('Art', 'Art'), ('Books', 'Books'), ('Fitness', 'Fitness'), ('Home & Garden', 'Home & Garden'), ('Transportation', 'Transportation'), ('Beauty', 'Beauty'), ('Pets', 'Pets'), ('Events', 'Events')], max_length=200),
        ),
    ]
